### ISSUE TITLE
Moving from GPL to Apache 2.0

### ISSUE THREAD

**Issue by alexauroradev** [cdot-network/DRN-sol#1]
For NEAR the standard is permissive license like Apache 2.0 or MIP or CC Zero. We're trying to be as far from GPL as possible to not to force our developers to use GPL too. Is it possible to change the license (and keep an eye on the dependencies)?

**Comment by madwiki** [comment]
I chose the same license with rainbow-bridge when I created this repository. So will the license of rainbow-bridge be changed as well? I would like to keep the same license with rainbow-bridge.

**Comment by djsatok** [comment]
It will be eventually changed to Apache 2.0 or something similar.

**Comment by madwiki** [comment]
OK, I will change it to  Apache 2.0 in the next push.
